index.html
style.css

Fixes the rest of the responsiveness issues. 
Closes #XXXXX

Responsiveness again

---

index.html
views/certs.html
views/connect.html
views/contribs.html
views/projects.html

This PR enables analytics for the pages. 
Closes #XXXXX

Enable Google Analytics

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/calendar/calendar.component.css
src/app/calendar/calendar.component.html
src/app/calendar/calendar.component.spec.ts
src/app/calendar/calendar.component.ts
src/app/header/header.component.html
src/index.html

Adds my Calendly to the website.
Closes #XXXXX

Add calendar page

---

src/app/calendar/calendar.component.ts
src/index.html

Fixes the load issue with the Calendly embed. 
Closes #XXXXX

Fix calendar load

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/contact/contact.component.css
src/app/contact/contact.component.html
src/app/contact/contact.component.spec.ts
src/app/contact/contact.component.ts
src/app/header/header.component.html

Adds a Formspree contact form to the page, allowing the deprecation of my server-based form.
Closes #XXXXX

new contact form

---

src/assets/data/Featured.ts

Fixes a broken link on the social DB project.
Closes #XXXXX

Fix broken social link

---

src/index.html

Adds Open Graph metadata (which is what powers Discord's embed feature) to the page.
Closes #XXXXX

Add Open Graph data

---

src/app/home/home.component.css
src/app/home/home.component.html
src/app/projects/projects.component.html

Changes the link to live versions from a standard link to a button, like the code.
Closes #XXXXX

Add button to view project

---

src/index.html
src/styles.css

* Update OpenGraph image data
* Implement custom scroll bar
Closes #38

Custom scrollbar, fix og image

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/header/header.component.html
src/app/sponsors/sponsors.component.css
src/app/sponsors/sponsors.component.html
src/app/sponsors/sponsors.component.spec.ts
src/app/sponsors/sponsors.component.ts

Adds a `sponsors` page to recognise folks who sponsor at the $10 tier or higher.
Closes #XXXXX

Add sponsors page

---

src/assets/data/Featured.ts

Updates the discord bot links
Closes #XXXXX

Replace bot links

---

.github/FUNDING.yml
README.md
SECURITY.md
src/app/connect/connect.component.html
src/app/header/header.component.html
src/app/sponsors/sponsors.component.html
src/assets/data/Social.ts

* Adds my custom chat link to the page and docs
* Removes Discord link and embed
* Adds PayPal to `funding.yml`
Closes #XXXXX

Add chat link, remove Discord, add PayPal

---

src/app/projects/projects.component.css

Resolves the issue where the custom buttons would overlap on smaller
screens.
Closes #50

fix: Inline-block buttons

---

src/app/app-routing.module.ts
src/app/calendar/calendar.component.html
src/app/header/header.component.html

feat: Add services

---

.github/dependabot.yml
.github/workflows/node.yml
karma.conf.js
package.json
src/app/app.component.spec.ts
src/app/calendar/calendar.component.spec.ts
src/app/certifications/certifications.component.html
src/app/certifications/certifications.component.spec.ts
src/app/connect/connect.component.html
src/app/connect/connect.component.spec.ts
src/app/contact/contact.component.spec.ts
src/app/header/header.component.html
src/app/header/header.component.spec.ts
src/app/header/toggle-button/toggle-button.component.spec.ts
src/app/home/home.component.html
src/app/home/home.component.spec.ts
src/app/projects/projects.component.html
src/app/projects/projects.component.spec.ts
src/app/sponsors/sponsors.component.html
src/app/sponsors/sponsors.component.spec.ts
src/app/toggle-side-nav.service.spec.ts

Builds out tests, enables in CI, activates Dependabot.
Closes #XXXXX

tools: enable testing

---

package-lock.json
package.json
src/assets/data/Social.ts

Adds my YouTube channel and Twitch links. @Vyvy-vi and @EddieJaoude are encouraging me to start using these, so I might as well.
Closes #XXXXX

feat: add social links

---

package-lock.json
package.json
src/app/calendar/calendar.component.html
src/app/connect/connect.component.css
src/app/connect/connect.component.html
src/app/connect/connect.component.spec.ts
src/assets/data/Social.ts

- Removes the defined pricing from the services page
- Adds description to the socials page
- Expands testing on socials component
Closes #XXXXX

feat: modify services and social

---

src/assets/data/Sponsors.ts

Woohoo! First sponsor!
Closes #XXXXX

feat: add first sponsor!

---

src/app/header/header.component.css

Adds a scroll to the sidebar as needed.
Fixes the issue with the nav bar not being scrollable.
Closes #XXXXX

fix: scroll on sidebar

---

src/assets/data/Projects.ts

Links for Timezone Calculator projects are now fixed:
- ~~https://www.nhcarrigan.com/timezone-calculator~~ -> https://www.nhcarrigan.com/timezone-chart/
- ~~https://github.com/nhcarrigan/timezone-calculator~~ -> https://github.com/nhcarrigan/timezone-chart
Closes #113

[FIX] Links for Timezone Calculator project

---

src/assets/data/Projects.ts

Changed the title and added required links to liveUrl and codeUrl
Closes #131

Updated Project.ts

---

package-lock.json
package.json
src/assets/data/Projects.ts

`https://beccalyria.nhcarrigan.com` was unreachable. The link was updated with `https://www.beccalyria.com/`

Fixed Becca Lyria liveUrl

---

.github/workflows/node.yml
package-lock.json
package.json
src/app/app.component.spec.ts
src/app/app.module.ts
src/app/calendar/calendar.component.spec.ts
src/app/certifications/certifications.component.spec.ts
src/app/connect/connect.component.spec.ts
src/app/contact/contact.component.spec.ts
src/app/header/audio/audio.component.css
src/app/header/audio/audio.component.html
src/app/header/audio/audio.component.spec.ts
src/app/header/audio/audio.component.ts
src/app/header/header.component.html
src/app/header/header.component.spec.ts
src/app/header/toggle-button/toggle-button.component.spec.ts
src/app/home/home.component.spec.ts
src/app/projects/projects.component.spec.ts
src/app/sponsors/sponsors.component.spec.ts

Adds an audio play button to the sidebar. This plays the great fairy fountain song! 😁 
Closes #XXXXX

feat: audio

---

.eslintrc.json
package-lock.json
package.json
src/app/app.component.ts
src/app/app.module.ts
src/main.ts

Enable Sentry logging on the site.
Closes #XXXXX

feat: enable Sentry

---

package-lock.json
package.json
src/app/header/header.component.html
src/app/header/toggle-button/toggle-button.component.html
src/index.html
src/styles.css

Fix some opportunities presented by lighthouse.
Closes #XXXXX

fix: lighthouse opportunities

---

package-lock.json
package.json
src/index.html

Add meta tags for the twitter card embed.
Closes #XXXXX

fix: twitter meta information

---

package-lock.json
package.json
src/app/work/work.component.css
src/app/work/work.component.html

- Add spacing between projects in the `work` component to avoid image overlap
- Add spacing between the modal buttons in the `work` component
Closes #330
Closes #331

fix: issues

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/four-oh-four/four-oh-four.component.css
src/app/four-oh-four/four-oh-four.component.html
src/app/four-oh-four/four-oh-four.component.spec.ts
src/app/four-oh-four/four-oh-four.component.ts
src/index.html

Add a 404 fallback route. Also fix typos in the meta data.
Closes #XXXXX

feat: routing

---

package-lock.json
package.json
src/app/home/home.component.html
src/app/home/home.component.spec.ts
src/app/home/home.component.ts

Update the dependencies all at once.
Closes #XXXXX

chore: update deps

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/privacy/privacy.component.css
src/app/privacy/privacy.component.html
src/app/privacy/privacy.component.spec.ts
src/app/privacy/privacy.component.ts
src/app/terms/terms.component.html
src/app/terms/terms.component.spec.ts
src/app/terms/terms.component.ts

Create generic policies to use when apps don't have a specific one.
Closes #XXXXX

feat: policies

---

README.md

- Update copyright year in `README.md`.

Update copyright year in `README.md`

---

index.html

Fixes some accessibility concerns found via https://wave.webaim.org
Closes #XXXXX

fix: accessibility

---

index.html

- Remove Alexander from the sponsors' list.
- They're not Nicholas' sponsor anymore.

fix: Remove Alexander from the sponsors' list

---

index.html
sponsor.html

Add a sponsors page with links to donate.
Closes #XXXXX

feat: add sponsor page

---

index.html

feat: add widgetbot

---

assets/css/styles.css
index.html

Adds a new sponsor, brightens the link text, adds colour to the date text based on tier.
Closes #XXXXX

feat: sponsor tweaks

---

sponsor.html

Now that Ko-fi supports memberships + rewards like Patreon, we can move it into the monthly donation section.
Closes #XXXXX

feat: move kofi button

---

sponsor.html

Missed these oops.
Closes #XXXXX

fix: meta tags on sponsor page

---

404.html
index.html
sponsor.html

feat: re-enable google analytics

---

index.html

- Update experience section
- Update social links
- Update sponsors
Closes #XXXXX

feat: general updates

---

404.html
games.html
index.html
sponsor.html

feat: add analytics

---

.gitignore
index.html
verify.txt

List more socials for verification purposes
Closes #XXXXX

feat: update identities

---

assets/css/styles.css
index.html

Let's put this back.
Closes #XXXXX

feat: transparency

---

confirm.html
index.html

feat: add meeting scheduling

---

verify.txt

feat: update discord username

---

assets/css/bots.css
bots.html
index.html

Adds a page to list most of the bots I work on.
Closes #XXXXX

feat: bots bots bots

---

assets/css/art.css

Changes the position of the art in the grid.
Closes #XXXXX

fix: art positioning

---

404.html
README.md
art.html
bots.html
confirm.html
emotes.html
games.html
index.html
sponsor.html

Updates the metadata for each page to say Naomi Carrigan instead of nhcarrigan.
Closes #XXXXX

chore: name in metadata

---

verify.txt

feat: add mastodon + tumblr

---

package-lock.json
package.json
src/app/activity.service.spec.ts
src/app/activity.service.ts
src/app/app.module.ts
src/app/arena/arena.component.html
src/app/arena/arena.component.spec.ts
src/app/arena/arena.component.ts
src/interfaces/Activity.ts

Adds the real-time activity view to the Arena.
Closes #XXXXX

feat: activity page

---

README.md
angular.json

chore: update domain name

---

src/index.html

fix: twitter meta

---

package-lock.json
package.json
src/app/app-routing.module.ts

release: v2.0.0

---

src/index.html

fix: lazy load nes-css

---

src/assets/data/outfits.ts

chore: found some more credit links

---

generateJson.js
package-lock.json
package.json

feat: load full outfit data into JSON

---

generateJson.js
src/assets/data/adventures.json
src/assets/data/emotes.json
src/assets/data/outfits.json
src/assets/data/portraits.json

feat: add json for other assets

---

loadFiles.js
resetFiles.js
src/app/_data/outfits.ts
src/app/museum/museum.component.spec.ts
src/app/reference/reference.component.spec.ts
src/app/tailor/tailor.component.spec.ts
src/app/training-hall/training-hall.component.spec.ts
src/assets/fileList.ts

chore: clothing

---

src/app/_data/outfits.ts

chore: new outfits

---

src/app/_data/outfits.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/confessional/confessional.component.html
src/app/confessional/confessional.component.spec.ts
src/app/confessional/confessional.component.ts
src/app/plaza/plaza.component.html
src/app/plaza/plaza.component.spec.ts

feat: add confessional component

---

.deepsource.toml
loadFiles.js
src/app/app.component.html
src/app/app.component.ts
src/app/arena/arena.component.html
src/app/arena/arena.component.spec.ts
src/app/arena/arena.component.ts
src/app/castle/castle.component.spec.ts
src/app/castle/castle.component.ts
src/app/confessional/confessional.component.spec.ts
src/app/confessional/confessional.component.ts
src/app/confirm/confirm.component.spec.ts
src/app/confirm/confirm.component.ts
src/app/landing/landing.component.ts
src/app/library/library.component.ts
src/app/lost/lost.component.ts
src/app/museum/museum.component.ts
src/app/plaza/plaza.component.ts
src/app/reference/reference.component.html
src/app/reference/reference.component.ts
src/app/tailor/tailor.component.ts
src/app/tavern/tavern.component.ts
src/app/temple/temple.component.ts
src/app/training-hall/training-hall.component.spec.ts
src/app/training-hall/training-hall.component.ts

chore: cleanup

---

src/app/app.component.ts
src/app/museum/museum.component.html
src/app/museum/museum.component.spec.ts
src/app/museum/museum.component.ts
src/environments/environment.ts

chore: more clean

---

src/app/_data/reference.ts
src/app/reference/reference.component.html
src/app/reference/reference.component.ts

chore: last bit of cleanup

---

src/index.html

feat: add crisp chat

---

src/app/training-hall/training-hall.component.html
src/app/training-hall/training-hall.component.spec.ts

feat: add link to game queue

---

src/app/_data/socials.ts
src/assets/data/verify.txt

chore: replace twitter links with mastodon

---

src/app/assets.service.ts
src/app/museum/museum.component.html
src/app/museum/museum.component.spec.ts
src/app/museum/museum.component.ts
src/app/training-hall/training-hall.component.html
src/app/training-hall/training-hall.component.spec.ts
src/interfaces/Adventure.ts
src/interfaces/Assets.ts
src/interfaces/Emote.ts
src/interfaces/Pose.ts

feat: use new asset layout

---

src/app/landing/landing.component.css
src/app/landing/landing.component.html

feat: add avatar on landing

---

src/assets/data/verify.txt

chore: update socials

---

src/app/museum/museum.component.ts
src/app/tailor/tailor.component.html
src/app/tailor/tailor.component.ts
src/app/training-hall/training-hall.component.ts

feat: randomise initial asset on component load

---

src/app/museum/museum.component.html
src/app/museum/museum.component.spec.ts
src/app/museum/museum.component.ts
src/app/tailor/tailor.component.html
src/app/tailor/tailor.component.ts
src/app/training-hall/training-hall.component.html
src/app/training-hall/training-hall.component.spec.ts
src/app/training-hall/training-hall.component.ts

feat: add buttons to get random assets

---

src/assets/data/verify.txt

feat: add new socials

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/council/council.component.html
src/app/council/council.component.spec.ts
src/app/council/council.component.ts
src/app/plaza/plaza.component.html
src/app/plaza/plaza.component.spec.ts

feat: add council component

---

src/app/museum/museum.component.html
src/app/tailor/tailor.component.html
src/app/training-hall/training-hall.component.html

chore: render data once loaded

---

src/assets/data/verify.txt
src/data/socials.ts

chore: update server information in socials

---

.github/workflows/code-ql.yml
.github/workflows/deploy.yml
.github/workflows/node-ci.yml
package.json

 chore: move to node 20

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/assets.service.ts
src/app/partners/partners.component.css
src/app/partners/partners.component.html
src/app/partners/partners.component.spec.ts
src/app/partners/partners.component.ts
src/app/plaza/plaza.component.html
src/app/plaza/plaza.component.spec.ts
src/interfaces/Assets.ts
src/styles.css

feat: add partners component

---

src/assets/data/verify.txt
src/data/socials.ts

chore: deleted socials

---

src/app/reference/reference.component.css
src/app/reference/reference.component.html
src/app/reference/reference.component.spec.ts

feat: add reference sheet image

---

src/app/reference/reference.component.html
src/app/reference/reference.component.spec.ts

feat: add colour palette to reference page

---

src/app/temple/temple.component.html
src/app/temple/temple.component.spec.ts

feat: add note for role, buttons for twitch and discord
